import assert from "node:assert/strict";
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const repoRoot = process.cwd();
const indexPath = join(repoRoot, "index.html");
const readmePath = join(repoRoot, "README.md");
const nojekyllPath = join(repoRoot, ".nojekyll");
const jataPath = join(repoRoot, "assets", "jata-negara.svg");
const portraitPath = join(repoRoot, "assets", "mohamad-nurakmal.png");

assert.ok(existsSync(indexPath), "index.html should exist");
assert.ok(existsSync(readmePath), "README.md should exist");
assert.ok(existsSync(nojekyllPath), ".nojekyll should exist");
assert.ok(existsSync(jataPath), "Jata Negara logo asset should exist");
assert.ok(existsSync(portraitPath), "Presenter portrait asset should exist");
assert.equal(statSync(nojekyllPath).size, 0, ".nojekyll should be empty");
assert.ok(statSync(jataPath).size > 10000, "Jata Negara SVG should not be an empty placeholder");
assert.ok(statSync(portraitPath).size > 100000, "Presenter portrait should not be an empty placeholder");

const html = readFileSync(indexPath, "utf8");
const readme = readFileSync(readmePath, "utf8");
const htmlBodyBlock = html.match(/html,\s*\n\s*body\s*{[^}]*}/)?.[0] ?? "";
const slideBlock = html.match(/\.slide\s*{[^}]*}/)?.[0] ?? "";

assert.equal((html.match(/<section class="slide/g) || []).length, 12, "deck should contain 12 slides");
assert.match(html, /<title>Slide Akmal V1<\/title>/);
assert.match(html, /<h1 class="slide-title" id="slide-1-title">Slide Akmal V1<\/h1>/);
assert.match(html, /Template pembentangan baharu dengan gaya Custom Gemini AUD/);
assert.match(html, /Pembentangan oleh Mohamad Nurakmal bin Ab Rasid\./);
assert.match(html, /aria-label="Slide Akmal V1"/);
assert.match(html, /assets\/jata-negara\.svg/);
assert.match(html, /assets\/mohamad-nurakmal\.png/);
assert.match(html, /class="brand-logo"/);
assert.match(html, /class="gemini-badge"/);
assert.match(html, /class="portrait-photo"/);
assert.match(html, /Mohamad Nurakmal bin Ab Rasid/);
assert.match(html, /@keyframes portraitFloat/, "portrait should have a looping motion treatment");
assert.match(html, /@keyframes geminiTwinkle/, "Gemini mark should have a looping motion treatment");
assert.match(html, /@keyframes gridDrift/, "deck should include subtle background motion");
assert.match(html, /@keyframes progressSheen/, "deck should animate progress feedback");
assert.match(html, /rel="icon" href="assets\/jata-negara\.svg"/, "page should use the Jata Negara asset as favicon");
assert.match(html, /id="progressBar"/);
assert.match(html, /id="slideCounter"/);
assert.match(html, /id="slideDots"/, "deck should include visible 1-12 progress dots");
assert.match(html, /--page:\s*#ffffff/, "deck should use a true white page token");
assert.match(html, /--topbar-h:\s*72px/, "deck should reserve a stable topbar height");
assert.match(html, /--controls-h:\s*72px/, "deck should reserve a stable controls height");
assert.match(html, /height:\s*100svh/, "app shell should lock to the browser viewport height");
assert.match(html, /height:\s*calc\(100svh - var\(--topbar-h\) - var\(--controls-h\)\)/, "deck should fill the remaining viewport height");
assert.match(html, /\.slide\s*{[\s\S]*?height:\s*100%;[\s\S]*?min-height:\s*0;[\s\S]*?overflow:\s*hidden;/, "each slide should be viewport-contained");
assert.match(htmlBodyBlock, /overflow:\s*hidden;/, "body should remain viewport-locked");
assert.doesNotMatch(slideBlock, /min-height:\s*auto;/, "base slides must stay constrained to the viewport");
assert.doesNotMatch(html, /@media[\s\S]*?\.slide\s*{\s*min-height:\s*auto;/, "mobile slides must stay constrained to the viewport");
assert.match(html, /location\.hash = `#\$\{current \+ 1\}`/);
assert.match(html, /case "ArrowRight":/);
assert.match(html, /case "ArrowLeft":/);
assert.match(html, /case "Home":/);
assert.match(html, /case "End":/);
assert.match(html, /window\.scrollTo\(0, 0\)/, "slide changes should reset scroll position for mobile");
assert.ok((html.match(/data-copy-target/g) || []).length >= 2, "copy buttons should be present");
assert.match(html, /navigator\.clipboard\.writeText/);
assert.match(html, /navigator\.clipboard && window\.isSecureContext/, "copy should guard Clipboard API availability before writeText");
assert.match(html, /document\.execCommand\("copy"\)/, "copy should include textarea fallback");

assert.match(readme, /^# SlideAkmalV1/m);
assert.match(readme, /Slide Akmal V1/);
assert.match(readme, /https:\/\/akmal4244\.github\.io\/SlideAkmalV1\//);
assert.match(readme, /GitHub Pages/);
