import assert from "node:assert/strict";
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const repoRoot = process.cwd();
const indexPath = join(repoRoot, "index.html");
const readmePath = join(repoRoot, "README.md");
const nojekyllPath = join(repoRoot, ".nojekyll");
const jataPath = join(repoRoot, "assets", "jata-negara.svg");
const portraitPath = join(repoRoot, "assets", "mohamad-nurakmal.png");
const codePhotoPath = join(repoRoot, "assets", "photo-code-laptop.jpg");
const sheetPhotoPath = join(repoRoot, "assets", "photo-spreadsheet.jpg");
const workspacePhotoPath = join(repoRoot, "assets", "photo-workspace-code.jpg");

assert.ok(existsSync(indexPath), "index.html should exist");
assert.ok(existsSync(readmePath), "README.md should exist");
assert.ok(existsSync(nojekyllPath), ".nojekyll should exist");
assert.ok(existsSync(jataPath), "Jata Negara logo asset should exist");
assert.ok(existsSync(portraitPath), "Presenter portrait asset should exist");
assert.ok(existsSync(codePhotoPath), "Real coding photo should exist");
assert.ok(existsSync(sheetPhotoPath), "Real spreadsheet photo should exist");
assert.ok(existsSync(workspacePhotoPath), "Real workspace photo should exist");
assert.equal(statSync(nojekyllPath).size, 0, ".nojekyll should be empty");
assert.ok(statSync(jataPath).size > 10000, "Jata Negara SVG should not be an empty placeholder");
assert.ok(statSync(portraitPath).size > 100000, "Presenter portrait should not be an empty placeholder");
assert.ok(statSync(codePhotoPath).size > 25000, "Coding photo should not be an empty placeholder");
assert.ok(statSync(sheetPhotoPath).size > 25000, "Spreadsheet photo should not be an empty placeholder");
assert.ok(statSync(workspacePhotoPath).size > 25000, "Workspace photo should not be an empty placeholder");

const html = readFileSync(indexPath, "utf8");
const readme = readFileSync(readmePath, "utf8");
const htmlBodyBlock = html.match(/html,\s*\n\s*body\s*{[^}]*}/)?.[0] ?? "";
const slideBlock = html.match(/\.slide\s*{[^}]*}/)?.[0] ?? "";

assert.equal((html.match(/<section class="slide/g) || []).length, 21, "deck should contain 21 slides");
assert.match(html, /<html lang="ms-MY">/);
assert.match(html, /<title>Slide Akmal V1<\/title>/);
assert.match(html, /<h1 class="slide-title" id="slide-1-title">Cipta Sistem Percuma<\/h1>/);
assert.match(html, /Panduan membina sistem ringkas menggunakan alat percuma/);
assert.match(html, /Bahasa Melayu Malaysia/);
assert.match(html, /ayat yang tertib, jelas dan diplomatik/);
assert.match(html, /Google AI Studio/);
assert.match(html, /Antigravity/);
assert.match(html, /Google Sheets/);
assert.match(html, /Google Apps Script/);
assert.match(html, /GitHub Pages/);
assert.match(html, /Cloudflare Pages/);
assert.match(html, /CORS/);
assert.match(html, /doGet\(e\)/);
assert.match(html, /doPost\(e\)/);
assert.match(html, /prompt-sistem-penuh/);
assert.match(html, /Bina satu sistem ringkas/);
assert.match(html, /Prompt terus untuk copy paste/);
assert.match(html, /Anda bertindak sebagai pembangun sistem web yang sabar/);
assert.match(html, /sama seperti contoh kelas/);
assert.match(html, /Pembina prompt interaktif/);
assert.match(html, /id="system-name-input"/);
assert.match(html, /id="system-purpose-input"/);
assert.match(html, /id="system-users-input"/);
assert.match(html, /id="system-features-input"/);
assert.match(html, /id="system-fields-input"/);
assert.match(html, /id="system-auth-select"/);
assert.match(html, /id="system-publish-select"/);
assert.match(html, /id="system-script-url-input"/);
assert.match(html, /class="prompt-builder"/);
assert.match(html, /collectBuilderValues/);
assert.match(html, /normalizeListInput/);
assert.match(html, /buildSystemPrompt/);
assert.match(html, /updateGeneratedPrompt/);
assert.match(html, /Setup automatik Google Sheets dan Apps Script/);
assert.match(html, /id="apps-script-output"/);
assert.match(html, /data-copy-target="apps-script-output"/);
assert.match(html, /buildAppsScriptCode/);
assert.match(html, /updateAppsScriptCode/);
assert.match(html, /refreshGeneratedOutputs/);
assert.match(html, /SpreadsheetApp\.getActiveSpreadsheet/);
assert.match(html, /function setupSheets\(\)/);
assert.match(html, /function doGet\(e\)/);
assert.match(html, /function doPost\(e\)/);
assert.match(html, /getOrCreateSheet_/);
assert.match(html, /ContentService\.createTextOutput/);
assert.match(html, /JSON\.stringify/);
assert.match(html, /contacts/);
assert.match(html, /data-builder-field/);
assert.match(html, /addEventListener\("input", refreshGeneratedOutputs\)/);
assert.match(html, /addEventListener\("change", refreshGeneratedOutputs\)/);
assert.match(html, /Pembentangan oleh Mohamad Nurakmal bin Ab Rasid\./);
assert.match(html, /aria-label="Slide Akmal V1"/);
assert.match(html, /fonts\.googleapis\.com\/css2\?family=Plus\+Jakarta\+Sans/);
assert.match(html, /font-family:\s*"Plus Jakarta Sans"/);
assert.match(html, /assets\/jata-negara\.svg/);
assert.match(html, /assets\/mohamad-nurakmal\.png/);
assert.match(html, /assets\/photo-code-laptop\.jpg/);
assert.match(html, /assets\/photo-spreadsheet\.jpg/);
assert.match(html, /assets\/photo-workspace-code\.jpg/);
assert.ok((html.match(/class="[^"]*real-photo/g) || []).length >= 3, "deck should include real photos in the slides");
assert.match(html, /class="brand-logo"/);
assert.match(html, /class="gemini-badge"/);
assert.match(html, /class="portrait-photo"/);
assert.match(html, /Mohamad Nurakmal bin Ab Rasid/);
assert.match(html, /@keyframes portraitFloat/, "portrait should have a looping motion treatment");
assert.match(html, /@keyframes geminiTwinkle/, "Gemini mark should have a looping motion treatment");
assert.match(html, /@keyframes gridDrift/, "deck should include subtle background motion");
assert.match(html, /@keyframes progressSheen/, "deck should animate progress feedback");
assert.match(html, /rel="icon" href="assets\/jata-negara\.svg"/, "page should use the Jata Negara asset as favicon");
assert.match(html, /id="progressBar"/);
assert.match(html, /id="slideCounter"/);
assert.match(html, /<div class="counter-pill" id="slideCounter">1 \/ 21<\/div>/);
assert.match(html, /id="slideDots"/, "deck should include visible 1-12 progress dots");
assert.match(html, /--page:\s*#ffffff/, "deck should use a true white page token");
assert.match(html, /--topbar-h:\s*72px/, "deck should reserve a stable topbar height");
assert.match(html, /--controls-h:\s*72px/, "deck should reserve a stable controls height");
assert.match(html, /height:\s*100svh/, "app shell should lock to the browser viewport height");
assert.match(html, /height:\s*calc\(100svh - var\(--topbar-h\) - var\(--controls-h\)\)/, "deck should fill the remaining viewport height");
assert.match(html, /\.slide\s*{[\s\S]*?height:\s*100%;[\s\S]*?min-height:\s*0;[\s\S]*?overflow:\s*hidden;/, "each slide should be viewport-contained");
assert.match(html, /\.slide-title\s*{[\s\S]*?text-wrap:\s*balance;/, "slide headings should use balanced wrapping");
assert.match(html, /\.lead\s*{[\s\S]*?font-size:\s*clamp\(1\.02rem,\s*1\.46vw,\s*1\.22rem\)/, "lead copy should use a polished presentation scale");
assert.match(htmlBodyBlock, /overflow:\s*hidden;/, "body should remain viewport-locked");
assert.doesNotMatch(slideBlock, /min-height:\s*auto;/, "base slides must stay constrained to the viewport");
assert.doesNotMatch(html, /@media[\s\S]*?\.slide\s*{\s*min-height:\s*auto;/, "mobile slides must stay constrained to the viewport");
assert.match(html, /location\.hash = `#\$\{current \+ 1\}`/);
assert.match(html, /case "ArrowRight":/);
assert.match(html, /case "ArrowLeft":/);
assert.match(html, /case "Home":/);
assert.match(html, /case "End":/);
assert.match(html, /window\.scrollTo\(0, 0\)/, "slide changes should reset scroll position for mobile");
assert.ok((html.match(/data-copy-target/g) || []).length >= 5, "copy buttons should be present");
assert.ok((html.match(/<textarea/g) || []).length >= 4, "copyable prompt text boxes should be present");
assert.match(html, /class="copy-textbox"/);
assert.match(html, /navigator\.clipboard\.writeText/);
assert.match(html, /target\.value/);
assert.match(html, /navigator\.clipboard && window\.isSecureContext/, "copy should guard Clipboard API availability before writeText");
assert.match(html, /document\.execCommand\("copy"\)/, "copy should include textarea fallback");
assert.match(html, /Papan kekunci: Kanan, Kiri, Home, End/);
assert.doesNotMatch(html, />[^<]*(Keyboard|live page|Deck asas|Template pembentangan|public repo|Checklist sebelum|Link GitHub Pages)[^<]*</, "visible copy should be Malay Malaysia first");
assert.doesNotMatch(readme, /\bdeck\b|keyboard|fullscreen|layout|viewport|push|branch|live page/i, "README should avoid unnecessary English terms");

assert.match(readme, /^# SlideAkmalV1/m);
assert.match(readme, /Slide Akmal V1/);
assert.match(readme, /Cipta Sistem Percuma/);
assert.match(readme, /Google Sheets/);
assert.match(readme, /Google Apps Script/);
assert.match(readme, /Apps Script automatik/);
assert.match(readme, /gambar sebenar/i);
assert.match(readme, /slide interaktif/i);
assert.match(readme, /https:\/\/akmal4244\.github\.io\/SlideAkmalV1\//);
assert.match(readme, /Bahasa Melayu Malaysia/);
assert.match(readme, /ayat diplomatik/);
assert.match(readme, /GitHub Pages/);
